feat(vault-agent): use caching to authenticate against vault
adfinis/vault-raft-backup-agent pull request #12
Opened 2022-10-29 17:45 UTC by pree

Uses vault agent's cache feature to authenticate against vault instead of using a sink file.

Not sure if we want it to replace the prior configuration, or add it as an additional option. What do think @in0rdr ?

Related to https://github.com/adfinis/vault-raft-backup-agent/issues/3

2022-10-31 07:06 UTC, tongpu commented
If you're breaking previous functionality it's major release, if you're just adding new features it's a minor release. :P

2022-11-02 15:42 UTC, in0rdr commented
Thanks @pree for that contribution.

I gave your changes a try in a test VM.

Works fine generally without the token sink, however, I have noticed some issues that absolutely need to be fixed:
* Move `cache` and `listener` stanza to the global level of the config file. These stanzas are not nested inside the `auto_auth` stanza.
* Disable tls in the listener of the agent

Without these changes, the agent is not booting.

Nice to have:
* Cleanup/remove unused variables in `default/main.yaml`
  * `vault_snapshot_token_location`
  * `vault_snapshot_token_mode`
* Use variable (`vault_snapshot_unix_listener` or similar) unix listener socket inside the system run directory of the agent instead of a fixed Port `8222` for the listener
* If a Port should be used, make it configurable through an Ansible variable (`vault_snapshot_tcp_listener` or similar)
* If we go crazy, we could even let the user choose between the tpc/unix listener

Personally, I prefer to provide the unix listener only.

Feel free to get back to me with a new iteration, I still have that test VM running.

Thanks

2022-11-02 15:43 UTC, in0rdr requested changes

2024-06-11 08:44 UTC, in0rdr commented
@pree are you still working on this PR? We can always have a look together.

2024-06-13 15:40 UTC, in0rdr commented on ansible/roles/vault-raft-backup-agent/templates/etc/systemd/system/vault-snap-agent.service.j2
> -ExecStart=/bin/sh -c 'VAULT_TOKEN="$$(cat /run/vault-snap-agent/token)" {{ vault_bin_path }}/vault operator raft snapshot save "{{ vault_snapshot_dir }}/{{ vault_snapshot_file_name }}"'
:sunglasses:

2024-06-13 16:00 UTC, in0rdr commented
@pree I noticed that the newest releases require us to implement it using the `vault proxy` command, see also:
* https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/apiproxy
* https://developer.hashicorp.com/vault/docs/agent-and-proxy/proxy/apiproxy

I know, quite confusing the whole story, but it works fine on my local test VM.

Maybe you will find the table here informative:
* https://developer.hashicorp.com/vault/docs/agent-and-proxy#introduce-vault-agent-and-vault-proxy-to-the-workflow

It basically shows that the only way for us to implement this functionality is using the new `vault proxy` command and migrate away from the old `vault agent` command (`vault agent` + `listener` will probably be removed soon, it's deprecated already, see https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/apiproxy#configuration-api_proxy).

To be honest, I'm still confused, even with the table :grin: But that's how it is..

I could not re-use the systemd runtime directory for the socket, because that directory is only created after the process starts (and Vault agent will not start if the directory is not created, so it's kind of chicken/egg). I put it now in `/etc/vault.d` because it needs to be in a directory writable for the `vault` user. It ried to put it in `/var/run/` as suggested in https://developer.hashicorp.com/vault/docs/agent-and-proxy/proxy/apiproxy#example-configuration but that only works when your process is root.

In any case, we got rid of `VAULT_TOKEN` :sunglasses: and the sink.

2024-06-13 16:12 UTC, in0rdr commented on ansible/roles/vault-raft-backup-agent/templates/etc/vault.d/vault_snapshot_agent.hcl.j2
> +  cache {
I moved the blocks to the top-level config. This way, the agent starts again.

2024-06-14 14:36 UTC, merged

2024-06-14 14:41 UTC, pree commented
Thanks for continuing this! I had a look through the changes and LGTM :) Let's see if we encounter any issues when running this.